version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
    tls:
      certificate: /certs/pdr-01.crt
      key: /certs/pdr-01.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
auth:
  token:
    realm: "https://pdr-01:5001/auth"
    service: "my.docker.registry"
    issuer: "Acme auth server"
    rootcertbundle: /certs/pdr-01.crt
